AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  getRoom:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 3
      Role: 'arn:aws:iam::958544629506:role/SudokuMultiplayerLambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:958544629506:layer:sudoku_multiplayer:6'
